"""data added

Revision ID: 558aff3b053e
Revises: afdfc163af61
Create Date: 2026-02-27 19:37:29.299113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558aff3b053e'
down_revision = 'afdfc163af61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encounter_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('encounter_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('patient_resp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('encounter_items', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('encounter_items')
        batch_op.drop_column('patient_resp')
        batch_op.drop_column('encounter_total')
        batch_op.drop_column('encounter_status')

    # ### end Alembic commands ###
