"""Added new fields for locations 

Revision ID: 6ee939787796
Revises: d8f35edcaf57
Create Date: 2026-02-26 16:29:02.448378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee939787796'
down_revision = 'd8f35edcaf57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'locations', ['current_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_location_id')

    # ### end Alembic commands ###
