"""Added new documenst fields  

Revision ID: 8caa7f6e515e
Revises: 6ee939787796
Create Date: 2026-02-26 18:23:36.637777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8caa7f6e515e'
down_revision = '6ee939787796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pverify_raw', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gemini_raw', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('gemini_raw')
        batch_op.drop_column('pverify_raw')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
