"""Added new fields for encounter queue

Revision ID: afdfc163af61
Revises: 8caa7f6e515e
Create Date: 2026-02-26 19:36:27.434560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdfc163af61'
down_revision = '8caa7f6e515e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_queue', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('in_queue')

    # ### end Alembic commands ###
