"""Added secondary insurance columns

Revision ID: b63f986ec164
Revises: 
Create Date: 2026-02-25 13:09:34.106673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63f986ec164'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sec_member_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sec_payer_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('sec_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sec_copay', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sec_coins', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sec_deductible_rem', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sec_oop_rem', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('sec_oop_rem')
        batch_op.drop_column('sec_deductible_rem')
        batch_op.drop_column('sec_coins')
        batch_op.drop_column('sec_copay')
        batch_op.drop_column('sec_status')
        batch_op.drop_column('sec_payer_name')
        batch_op.drop_column('sec_member_id')

    # ### end Alembic commands ###
