"""data added for ma

Revision ID: c4237d10a3c0
Revises: 558aff3b053e
Create Date: 2026-02-27 20:00:42.053667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4237d10a3c0'
down_revision = '558aff3b053e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encounter_flag', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('encounter_flag')

    # ### end Alembic commands ###
