"""new fieds for sec data is added 

Revision ID: fdaa89e3e53b
Revises: 74a1ba4714a3
Create Date: 2026-03-05 16:31:59.949100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdaa89e3e53b'
down_revision = '74a1ba4714a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.String(length=20), nullable=False),
    sa.Column('total_visit', sa.Float(), nullable=True),
    sa.Column('patient_responsibility', sa.Float(), nullable=True),
    sa.Column('insurance_contribution', sa.Float(), nullable=True),
    sa.Column('codes_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sec_pverify_raw', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('sec_pverify_raw')

    op.drop_table('saved_visits')
    # ### end Alembic commands ###
